TRACKING_CODE = "PRJ0000.X.X"
DB_PATHS = "MOCK/DATA"
PATTERN_PATH = "MOCK/PATTERN"
PATTERN_PATH_JSON = "MOCK/PATTERN/padrao_db.json"
OUTPUT_DB_PATH = "MOCK/OUTPUT_DB"
EXCLUDED_TABLES = {"android_metadata", "sqlite_sequence"}
EXCLUDED_COLUMNS = {""}
